- .github/ISSUE_TEMPLATE/doc_issue.yaml
Using [YAML forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema).
> Add a template for doc issues

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/feature_request.yaml
Currently when raising an issue or feature request, many of the inputs have the `shell` render type, which wraps the input in a code block with the `shell` language, you then have to go in and edit it after submitting. 
Removing these `render: shell` options makes it so you get the full markdown editor for the input, and can include your own code blocks as well as links and styling etc.
> Update issue templates to allow markdown

- examples/hello_interop.mojo
- examples/matmul.mojo
- examples/pymatmul.py
- examples/simple_interop.py
Fixes issue #515 and #514 
Will look for the modules in the current directory or `./examples`, in case the user is running from the root of the repo, and print an error if it can't find the required modules.
It will also install `numpy` if it's missing, as failing when missing a pip module currently doesn't give an informative error.
> Fix interop in examples

- proposals/lifetimes-and-provenance.md
expressivity -> expressiveness
> fix: typo in lifetimes-and-provenance.md

- examples/deviceinfo.mojo
The "CPU Features" row of the output from _mojo/examples/deviceinfo.mojo_ showed only one CPU feature (the last one detected). This fixes it.
> Fix deviceinfo.mojo: only the last found CPU feature was being shown

- examples/matmul.mojo
- examples/pymatmul.py
Generally no one is doing such a naive matmul I don't think, I'm thinking something like this is a bit more realistic. 
IMO, something like this is great to show that mojo has quite a bit to offer over numpy's matrix ops as well (a question that I had until I ran this)
```
$ mojo matmul.mojo
Python:        	   0.006 GFLOPS
Python (Numpy):	   1.603 GFLOPS
Naive:         	   5.920 GFLOPS         1052.24x faster than Python
Vectorized:    	  20.414 GFLOPS         3628.55x faster than Python
Parallelized:  	  43.906 GFLOPS         7804.28x faster than Python
Tiled:         	  47.673 GFLOPS         8473.98x faster than Python
Unrolled:      	  55.627 GFLOPS         9887.68x faster than Python
Accumulated:   	 436.572 GFLOPS        77601.01x faster than Python
```
> example/benchmarks: compare against numpy dot

- examples/docker/Dockerfile.mojosdk
First of all: Amazing jog! Congrats!
---
I had an error when I tried to run the Docker version:
The authentication fails. I believe Modular changes the way authentication works.
**My Setup:**
- Intel  i5-13600K
- 32 GB RAM
- WSL2 Ubuntu 22.04 LTS
- Windows 11 Pro Insider Preview x64 (v. 22H2  Build Windows 11 Pro Insider Preview)
- Docker Desktop 4.22.0 (117440)
**Replicating Steps:**
Inside docker directory:
```
docker compose up
```
Terminal Print:
```
127.3 sh: 80: [[: not found
127.3   __  __           _       _
127.3  |  \/  | ___   __| |_   _| | __ _ _ __
127.3  | |\/| |/ _ \ / _` | | | | |/ _` | '__|
127.3  | |  | | (_) | (_| | |_| | | (_| | |
127.3  |_|  |_|\___/ \__,_|\__,_|_|\__,_|_|
127.3 
127.3 Welcome to the Modular CLI!
127.3 For info about this tool, type "modular --help". …
```
> fix: Dockerfile Modular Auth

- README.md
The Mojo SDK is also available for local development, but there's no need to explain the differences here. Instead, we can just link to the get started guide that explains the latest Mojo SDK and Mojo Playground.
Fixes #1220
> De-emphasize Mojo Playground in the readme

- docs/changelog.md
- docs/faq.md
- docs/manual/python/types.ipynb
- docs/manual/values/ownership.ipynb
- docs/roadmap.md
- examples/blogs-videos/mojo-plotter/README.md
- examples/blogs-videos/whats_new_v0.5.ipynb
- examples/notebooks/RayTracing.ipynb
- examples/notebooks/programming-manual.ipynb
- proposals/mojo-and-dynamism.md
- workshops/mojo_for_python_developers/2_speeding_up_python.ipynb
- workshops/mojo_for_python_developers/3_parallelization_speedup_tensor_mean.ipynb
Found by running [`typos`](https://github.com/crate-ci/typos) with the following `_typos.toml` config:
```toml
[default.extend-words]
inout = "inout"
ND = "ND" # NDBuffer
nane = "nane" # Wrong on purpose in an example.
mis = "mis" # mis-features
```
> Fix a few typos in docs

- docs/manual/functions.ipynb
Under [Functions page](https://docs.modular.com/mojo/manual/functions.html), there is a link to the [Language basics page](https://docs.modular.com/mojo/manual/basics.html). Currently, clicking on the link, it shows `Page not found` due to the wrong URL (a slash is redundant at the end).
What has been fixed: Removed the redundant slash
Signed-off-by: Phuc Tran <phuc@bumbii.tech>
> Fix wrong link to Language basics page (on Functions page)

- docs/manual/lifecycle/life.ipynb
- docs/manual/parameters/index.ipynb
In the HeapArray example, set the "cap" size as the total allocation for the pointer rather than the "size" of the current allocated elements. 
Signed-off-by: Rahul D Shetty [35rahuldshetty@gmail.com](mailto:35rahuldshetty@gmail.com)
> docs and example update

- docs/manual/values/value-semantics.ipynb
Just a small spelling error, in the section titled "Value semantics in `def` vs `fn`".
> Fix typo under docs/manual/values/value-semantics.ipynb

- docs/changelog.md
- docs/manual/traits.ipynb
Some of the links in the docs still point to the old location of `DynamicVector`.
This patch intends to make the links point to the correct location.
> Fix broken vector links

- docs/manual/structs.ipynb
> Fix typo in structs.ipynb

- proposals/inferred-parameters.md
This PR submits a new proposal document reviewed by the "language committee" to introduce a new `inferred` keyword when declaring parameters. These parameters would only be inferrable from other parameters or arguments in a function, but are skipped when binding functions at callsites. This will enable autoparameterization of parameters and omitting redundant parameters when calling certain functions.
For example:
```python
fn scalar_func[inferred dt: DType, x: Scalar[dt]]() -> Scalar[dt]:
return x * 2
print(scalar_func[Int64(5)]())
```
> Submit proposal for new `inferred` parameters

- examples/nbody.mojo
Edit: I found a second optimisation unrolling the inner loop so the total improvement is 6.53 -> 1.13 seconds on M1 Pro.  That change is discussed in the next comment.
------------------
On M1 Pro the result of `benchmark()` falls from 6.53 to 4.40 seconds.  I realise this code is reproducing a specific benchmark but some of the other competitors do this optimisation so I think it is fine.
One of the [Julia code examples](https://benchmarksgame-team.pages.debian.net/benchmarksgame/program/nbody-julia-8.html) explains it well. 
```
@inbounds for i=1:4
bi = bodies[i]
iv = bi.v
for j=i+1:5
iv = iv .- Δx[k] .* (mag[k] * bodies[j].m)
bodies[j] = Body(bodies[j].x,
bodies[j].v .+ Δx[k] .* (mag[k] * bi.m),
bodies[j].m)
k += 1
end
bodies[i] = Body(bi.x, iv, bi.m)
end
```
> nbody.mojo - remove unnecessary memory writes and @unroll inner loop

- proposals/project-manifest-and-build-tool.md
This adds a proposal for a Mojo project manifest and build tool. Once merged into `main`, a GitHub Discussion will be posted, linking to the proposal, to facilitate feedback and further discussion.
> [proposals] Mojo project manifest and build tool

- proposals/project-manifest-and-build-tool.md
Add a link to the GitHub discussion for the Mojo project manifest and build tool.
> [proposals] Add link to GitHub discussion

- .github/workflows/buildAndTestMojoOSS.yml
This PR includes logic to download the modular installer and use it to install the mojo compiler.
> CI update to get the modular installer, install mojo compiler

- examples/notebooks/BoolMLIR.ipynb
Two small typo fixes:
1. `abstractons` -> `abstractions`
2. `builtin` -> `built-in`
> Fix typo in BoolMLIR.ipynb

- examples/notebooks/Matmul.ipynb
Two simple typo fixes:
- `take look at` -> `take a look at`
- delete an extra `the`
> Fix typo in Matmul.ipynb

- examples/notebooks/BoolMLIR.ipynb
Two changes occured in Mojo 2024.1.0 which made some code in this notebook deprecated:
* Using `let` now raises a warning. We should use `var` instead.
* Initializers for `@register_passable` values can (and should!) now be specified with inout self arguments just like memory-only types.
See the changelog here: https://docs.modular.com/mojo/changelog#v241-2024-02-29
We currently show deprecated syntax in the notebook in the documentation. See https://docs.modular.com/mojo/notebooks/BoolMLIR#compile-time-constants
> Update BoolMLIR.ipynb for Mojo 2024.1.0

- examples/mandelbrot.mojo
- examples/matmul.mojo
- examples/nbody.mojo
Soon, CI will enforce linting and formatting on any changed mojo files in prep for open sourcing the Standard Library.  So, go ahead and ensure the existing examples files adhere to `mojo format` from top-of-tree.
Produced by:
```
git ls-files '*.mojo' | xargs mojo format
```
> [Examples] Run `mojo format` on the examples

- .github/workflows/buildAndTestMojoOSS.yml
Add a step in the build and test workflow for ensuring any added or modified Mojo code adheres to `mojo format`.  Fail the step (and the GH workflow) if any code does not adhere to our existing formatting rules.  Right now, there's no `pyproject.toml` that `mojo format` or `mblack` uses under the hood — it's just the default line length of `80` set by `mojo format` and then the normal defaults of `mblack`.
The step is set up so we can easily extend it to running `markdownlint` for Markdown files in the future.
> [CI] Ensure `mojo format` in lint/format steps

- .github/workflows/examples.yml
- .gitignore
- examples/lit.cfg.py
- scripts/run-examples.sh
Add a `lit.cfg.py` in the `examples` directory which sets up the lit config for
example Mojo files (notebooks not yet supported).  Add a wrapper script,
`run-examples.sh` which creates a build directory and invokes `lit` using this
configuration.
Go one step further and create a GitHub workflow that puts all of the pieces
together to download the latest stable Mojo compiler and test the examples using
the provided script.
The `scripts/run-examples.sh` is something that can be run both locally and in
CI.
Add common artifacts to the `.gitignore` such as the new `build` directory, and
other Python-related things.
> [Examples] Add ability to run and test examples

- .github/workflows/buildAndTestMojoOSS.yml
- .github/workflows/examples.yml
To ensure the workflow triggers on all types of status changes under the `pull_request` trigger, explicitly specify all the state changes.
While here, go ahead and add our open-source license to the top of each workflow.
> [CI] Explicitly specify `types:` under PR section

- .github/workflows/buildAndTestMojoOSS.yml
The OSS workflow got broken in
https://github.com/modularml/mojo/commit/cb2144b80bfbe0a23536ebba996217d8facaa857 since the `uses:` grammar requires a ref or version.
Example CI failure:
```
the `uses' attribute must be a path, a Docker image, or owner/repo@ref
```
from https://github.com/modularml/mojo/actions/runs/8309422015
Fix this by explicitly specifying the latest tagged release of the `paths-filter` action.
While here, go ahead and add a `workflow_dispatch` trigger so this workflow can be manually run on a given branch.
> [CI] Specify SHA in use of `paths-filter` action

- .github/workflows/examples.yml
The `ubuntu-latest` Docker image already comes with Python 3.10 installed.  See the
[README](https://github.com/actions/runner-images/blob/4224f365e0fb518e4eb80364c5f2f7716578ea0a/images/ubuntu/Ubuntu2204-Readme.md) for the GitHub Docker image corresponding to `ubuntu-latest`.  Since we're not too privy on the exact Python version, just use the default.
> [CI] Skip `setup-python` step

- .github/workflows/buildAndTestMojoOSS.yml
- .github/workflows/examples.yml
Add a `permissions` section to all workflow files to allow third-party GitHub actions to have read permissions.  This will fix the issue where the `dorny/paths-filter` step doesn't have proper read permissions to query the file list modified in a pull request, resulting in a hard error from the GitHub APIs it uses.
> [CI] Add workflow permissions

- docs/manual/packages.md
Use `var` instead of `let`in `packages.md` file.
The reason is as follows:
> Mojo 24.1 removed support for let from the compiler IR (but it still parses let for migration), subsequent releases will remove the let keyword entirely.
Quote from https://github.com/modularml/mojo/discussions/1456#discussioncomment-8672522.
> Fix md: use var instead of let

- .github/workflows/examples.yml
- examples/lit.cfg.py
Install the `nightly/mojo` package and use it in the examples workflow. Additionally, specify to use the nightly compiler and pre-built packages in the `examples/lit.cfg.py`.
> [CI][Examples] Use `nightly/mojo` in workflow and examples

- .github/workflows/standard_library_tests_and_examples.yml
Currently, `examples.yml` only runs the examples, which was convenient for launching today.  Now that we've shipped the standard library though, augment the workflow file to also run the standard library tests.
While we're here, rename the name of the file, step, and name of the job to better reflect reality that this file is used to run the standard library tests and the examples now.
> [CI] Run standard library tests

- .github/workflows/standard_library_tests_and_examples.yml
Add some steps which ensure that any changes to mojo files pass our formatting checks.  Right now, the format is just `mojo format -l 80` on a list of the changed files.
It is designed this way to give space for markdown linting and formatting in the future too.
> [CI] Add lint and format step to workflow

- .github/workflows/standard_library_tests_and_examples.yml
Adds support for running the main PR examples and testing workflow on macOS runners. This improves our platform testing coverage in the automated CI checks.
> [stdlib] feature: Support for macOS CI testing

- .gitignore
It is nice to ignore `.DS_Store` for Mac developers.
> [Utils] Add `.DS_Store` to `.gitignore` for Mac developers

- stdlib/src/collections/__init__.mojo
Exports InlinedFixedVector form collections
Signed-off-by: Farhan Ali Raza <farhanalirazaazeemi@gmail.com>
> [mojo-stdlib] Export `InlinedFixedVector` from `collections`

- .github/CODEOWNERS
This adds a minimal CODEOWNERS file, for the new `/stdlib/` directory.
> feature: Add minimal initial CODEOWNERS

- .github/workflows/standard_library_tests_and_examples.yml
- stdlib/docs/development.md
- stdlib/docs/style-guide.md
The `mojo format` [command in the CI](https://github.com/modularml/mojo/blob/nightly/.github/workflows/standard_library_tests_and_examples.yml#L111) applies a limit of 80 chars with `-l 80`. This is not documented anywhere, resulting in broken formatting in pull requests. This PR fixes this issue.
> [docs] Fix wrong `mojo format` command, add `-l 80`.

- .github/workflows/standard_library_tests_and_examples.yml
- stdlib/docs/development.md
- stdlib/docs/style-guide.md
This reverts commit e305d91c2688432bacac4e72918d66541f57fec1.  As of the latest `nightly/mojo`, `mojo format` properly defaults its line length to `80` now instead of `88`.  This change didn't make it into the changelog yet, so I'll go write that up, but it did actually make it into today's `nightly/mojo` on April 8th.  So, go ahead and update the docs to no longer explicitly specify `-l 80` to `mojo format` everywhere.
> Revert "[docs] Fix wrong `mojo format` command, add `-l 80`. (#2158)"

- proposals/byte-as-uint8.md
> [Proposal] Standardise the representation of byte sequence as a sequence of unsigned 8 bit integers

- .pre-commit-config.yaml
Now that `mojo doc` command learned `--validate-doc-strings`, we don't need to have the wrapper script that inspects `stderr` that `mojo doc -diagnose-missing-doc-strings` previously used in the `check-docstrings.py`.
We'll update the docs in a separate PR since this `.pre-commit-config.yaml` isn't managed by Copybara.
> [tools] Simplify doc validation

- .pre-commit-config.yaml
Reverts modularml/mojo#2795.  Despite being simpler, `--validate-doc-strings` along isn't sufficient.  In order the doc strings to be enforced properly, we'd need to also specify `--diagnose-missing-doc-strings`.  This is a bit silly in principle (superfluous rather).  Moreover, it's not user-friendly since that option dumps all the JSON to `stdout` even if there are no errors.  So, revert this commit entirely since the developer experience was superior with the wrapper Python script for checking `stderr`.  I've started a conversation internally about this as it's not great either way currently.
> Revert "[tools] Simplify doc validation"

- .github/workflows/standard_library_tests_and_examples.yml
When trying to debug strange CI errors, it's helpful to know if the error happened in one OS or in all OSs. But currenty as soon as one of the build fails, the other are canceled. Let's always run all jobs until the end.
Motivating example: https://github.com/modularml/mojo/pull/2945 which I can't reproduce locally.
> [CI] Do not cancel other CI jobs when one of them failed

- .github/workflows/standard_library_tests_and_examples.yml
Resolves deprecation warning on runs e.g. https://github.com/modularml/mojo/actions/runs/9425680009
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v2.
> The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2.
Reference https://github.com/actions/checkout?tab=readme-ov-file#checkout-v4
(Rebase of https://github.com/modularml/mojo/pull/2987)
> [tools] Bump actions/checkout to v4

- .github/workflows/standard_library_tests_and_examples.yml
- .github/workflows/test_pre_commit.yml
We get two benefits from this:
1) We save ~30s on the unit test run
2) We have a better error reporting when something fail, we can quickly see that the linters were not run.
> [CI] Split unit tests and pre-commit tests in the CI

- .github/workflows/standard_library_tests_and_examples.yml
In https://github.com/modularml/mojo/pull/3234, when synced internally, only the `scripts` were added.  The modifications to the GitHub workflow didn't land in https://github.com/modularml/mojo/commit/b939aeab913b2a83f3343cec0c87717eb3f6ca1a since the `.github` directory isn't managed by Copybara currently.
So, this PR does the `.github` workflow cleanup part of https://github.com/modularml/mojo/pull/3234 now that https://github.com/modularml/mojo/commit/b939aeab913b2a83f3343cec0c87717eb3f6ca1a has landed.
> [CI] Use build scripts from CI workflows

- .github/ISSUE_TEMPLATE/doc_issue.yaml
This allows us to pre-fill the "where is the problem" field with a `url` parameter in the URL.
> Add `url` ID to docs issue template

- docs/manual/values/value-semantics.ipynb
I think "callee" should be "caller" in "any living variable from the callee is not affected by the function."
Signed-off-by: Greg Sullivan <gregs@sulliwood.org>
> [Docs] Typo: "callee" should be "caller" 

- .github/ISSUE_TEMPLATE/mojo_bug_report.yaml
> [issue-template] Update mojo issue template to reference magic instead of modular cli

- .pre-commit-config.yaml
a5a1e886139d2bc98c7f8c0e6bcada9ed6255818 changed the name of the `check-licenses.mojo` file, but this happened internally, and broke the external use of the name.  Fix this to account for the new name.
Note:
- We may want to change `check-docstrings.py` to comply with the new scheme, but we'll save that for later.
- This file isn't managed by copybara, so that's why this was subject to said breakage to begin with.
> [CI] Fix pre-commit filename use

- examples/lit.cfg.py
Some new examples that are being added are being tested as standalone `magic` projects, not with `lit`. Ignore these files from the lit config.
We may need to also add tests in CI for these separately, that could be a followup once we have some examples in place.
> [Lit][CI] Exclude mojo files in examples subdirectories from lit

- examples/lit.cfg.py
Lit config doesn't support wildcards _or_ directories, but it does support entire folders, so here we're just searching for every folder under `examples` and adding it to the exclude.
I ran a quick test by copying `hello_interop.mojo` to `examples/project` (and renaming to `hello_interop2.mojo` to ignore the current excludes), then running `magic run examples`. The new file was correctly ignored.
> [CI][Lit] Ignore subdirectories of "examples" in lit config

- docs/manual/get-started.mdx
"[...] requires that the method *cannot* raise and error, [...]" is grammatically incorrect (assumed typo)
> [docs] Fix typo
