modular/mojo

- proposals/mojo-and-dynamism.md
The doc was already shared via github discussions.
> Add Mojo and Dynamism as a proposal doc

- examples/mandelbrot.mojo
- examples/notebooks/Mandelbrot.ipynb
Example will also continue to work with release 0.2.0
> Fix tensor being destroyed before benchmark finished

- examples/mandelbrot.mojo
- examples/notebooks/Mandelbrot.ipynb
- examples/notebooks/Matmul.ipynb
> Mandelbrot and matmul improvements

- .github/ISSUE_TEMPLATE/dev_console_issue.yaml
- .github/ISSUE_TEMPLATE/modular_cli_issue.yaml
- .github/ISSUE_TEMPLATE/mojo_bug_report.yaml
- .github/ISSUE_TEMPLATE/mojo_feature_request.yaml
- Create issue templates for Modular CLI and Dev Console
- auto assign the appropriate labels at the time of issue creation
- Update the mojo bug report and FR templates
> [Issue Templates] Create issue templates for Modular CLI and Dev Console

- .github/ISSUE_TEMPLATE/dev_console_issue.yaml
- .github/ISSUE_TEMPLATE/modular_cli_issue.yaml
- .github/ISSUE_TEMPLATE/mojo_bug_report.yaml
- .github/ISSUE_TEMPLATE/mojo_feature_request.yaml
Add mojo label for Mojo Issues and standardize capitalization of bug templates
> Add mojo label for Mojo Issues and standardize capitalization of bug templates

- examples/notebooks/RayTracing.ipynb
Small fix for MLIR syntax changes
> Fix raytracing notebook

- examples/notebooks/Mandelbrot.ipynb
- examples/notebooks/Matmul.ipynb
Changes as of modularml/modular@c566bfa5dcdb0b42535c54edf46fb84f999abd16
> Update Mojo examples

- examples/mandelbrot.mojo
> Fix typo in mandelbrot.mojo

- examples/pymatmul.py
- examples/simple_interop.py
Replace deprecated find_loader with importlib.util.find_spec
> find_loader is deprecated

- proposals/README.md
Fixed minor grammatical error in README.md of proposals
> Fix: grammar in README.md

- README.md
Fixed #1184 
Added Contributors section to Readme.
@lattner  @jackos kindly view it and merged the PR. Thank You!
> Fixed: Added contributors section to README.md

- examples/blogs-videos/whats_new_v0.5.ipynb
This notebook was demonstrated in the following livestream:
https://www.youtube.com/live/9It-jK_GQdk?feature=shared
> Notebook showing what's new in v0.5

- examples/blogs-videos/mojo-matrix-slice.ipynb
Blog post: Implementing NumPy style matrix slicing in Mojo🔥
> Example supporting matrix slicing example blog post

- examples/matmul.mojo
- use `_` to iterate a variable that won't be used rather than defining `i` on two lines in a row
- omit the 0 starting value in `range` when its unnecessary
- use the `@unroll`decorator where possible
- group `alias` definitions near the start of the matmul example that uses them.  There are still some hidden in the nested tile functions but at least most are easier to find.
There is also the `M * 2` num_workers that  probably needs a comment or some other way to make it more obvious.  On my M1 Pro using just `M` was faster though the `swizzling` example generally did not show much performance improvement even after reducing the workers.  But I assume `M * 2` is a specific tweak that works well on some systems, might make large performance differences between examples, and might need to …
> improve readability in matmul examples

- docs/manual/get-started/hello-world.md
There's no dev tool yet to build the docs site to check, so hopefully this works.  :)
> Update link to language basics.  Fixes #1377.

- examples/docker/Dockerfile.mojosdk
Change the mojo installation command as per documentation.
> Minor Change in Dockerfile

- workshops/mojo_for_python_developers/2_speeding_up_python.ipynb
> Fix typo in 2_speeding_up_python.ipynb

- docs/changelog.md
- docs/manual/index.md
Changes as of modular@126e287e763f8904d80b8a9df1b8f9ce4705b869
> Update docs and examples post 0.6.1

- examples/matmul.mojo
This just makes it easy to change between float32 and float64 to test performance.
> Easily change between Float32 and Float64.

- docs/manual/lifecycle/index.ipynb
- docs/manual/lifecycle/life.ipynb
- docs/manual/parameters/index.ipynb
- docs/manual/traits.ipynb
- docs/manual/values/index.ipynb
- docs/manual/values/value-semantics.ipynb
Plus rewording of a few sentences to improve their clarity.
> Fix various typos in documentation

- examples/matmul.mojo
- examples/notebooks/Matmul.ipynb
Puts the public repo in sync with matmul improvements.
Fixes https://github.com/modularml/mojo/issues/1426
> Various matmul example improvements, remove accumulate implementation

- examples/blogs-videos/valentine.mojo
Simplifies main function by changing to `def` to remove compiler warnings on unused Python variables.
> Changing main from fn to def

- examples/blogs-videos/mojo_dunder/DunderArray.mojo
- examples/blogs-videos/mojo_dunder/dunder_notebook.ipynb
1. `dunder_notebook.ipynb` is a notebook that demonstrates dunder methods
2. `DunderArray.mojo` is a mojo file with a custom struct that implements all the dunder methods.
> Examples supporting blog post on Dunder methods

- examples/blogs-videos/max-blogpost-demos/build_run_docker.sh
- examples/blogs-videos/max-blogpost-demos/infer-max-serving.py
- examples/blogs-videos/max-blogpost-demos/max-engine-resnet50.py
Examples used in the blog post: https://www.modular.com/blog/getting-started-with-max-developer-edition
> Example files for blog post: Getting started with MAX

- examples/blogs-videos/max-optimize-deploy/client-max-webcam.py
- examples/blogs-videos/max-optimize-deploy/host-max-optimize-deploy.ipynb
host:
- notebook to deploy MAX Serving client:
- triton client to invoke endpoint
> notebook and python file supporting blog post

- docs/changelog.md
Tweaked some examples to better showcasing Mojo's new capabilities.
> Fix indentation in changelog.md

- README.md
Signed-off-by: Ali Yousefi iamaliyousefi@gmail.com
> [docs] Fix "write your first Mojo program" link

- .github/ISSUE_TEMPLATE/mojo_bug_report.yaml
> [docs] Improve `mojo_bug_report.yaml` issue template

- docs/tools/debugging.ipynb
> [docs] update debugging.ipynb

- proposals/byte-as-uint8.md
Add a proposal to standardize the representation of byte sequence as a sequence of unsigned 8 bit integers.
Signed-off-by: Maxim Zaks <maxim.zaks@gmail.com>
(cherry picked from commit 46889965656de7d4949f054e483335883a1f83e2)
> [stdlib] [proposal] Standardize the representation of byte sequence as a sequence of unsigned 8 bit integers (#2099)

- .github/ISSUE_TEMPLATE/doc_issue.yaml
- .github/ISSUE_TEMPLATE/modular_cli_issue.yaml
- .github/ISSUE_TEMPLATE/mojo_bug_report.yaml
- .github/ISSUE_TEMPLATE/mojo_feature_request.yaml
Update the default labels for the issues created via the issue-templates.
> [Issue template] Update the default labels for issues

- .github/PULL_REQUEST_TEMPLATE.md
Note that since nightly is not the default branch in github, this template won't be seen until the next release. This annoyance should be fixed if https://github.com/modularml/mojo/issues/2556 is addressed.
For more information about pull request templates: 
* https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates#pull-request-templates
* https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository
> [tools] Add a template for pull requests

- proposals/ref-convention.md
This is the proposal for the new ref conventions that Chris and I have been working on.
> [Proposals] Add proposal for ref convention

- README.md
Updates to fix links and clarify the license
Signed-off-by: Jack Clayton <jackos@me.com>
> [docs] Updates for Mojo README

- .gitignore
Copybara doesn't bring these files across, so raising PR directly to this repo
> [stdlib] Update gitignore for magic

- .gitignore
- examples/.gitignore
Similar to the MAX repo, we will be committing lockfiles soon.
> [stdlib][main] Un-ignore magic.lock files

- CONTRIBUTING.md
- README.md
- docs/changelog-released.md
- stdlib/docs/development.md
- stdlib/docs/internal/README.md
Update documentation for main branch getting nightly updates
> [docs] Update documentation for main branch getting nightly updates and stable added
